steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
          scripts/metaltile_cloud.sh
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: bash
  env:
  - 'JOB_NAME=metaltile-$BUILD_ID'
  - 'REPO_NAME=$REPO_NAME'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'REVISION_ID=$REVISION_ID'
  - 'COMIT_SHA=$COMMIT_SHA'
  args:
    - -c
    - |
          ./scripts/upload-job-config.sh